### ISSUE TITLE
Improve song selection picker

### ISSUE THREAD

**Issue by chrisglein** [brewingcode/shanties#11]
- [x] It's showing the file name, not the song name.
- [x] They're not alphabetized, which makes it unintuitive for picking a song.
- When viewing on a small screen (mobile) the drop down for the picker is cut off on the right side of the screen [NO REPRO]

**Comment by brewingcode** [comment]
#12 addresses the first and second todo

I don't know what "mobile" is. Is that something that hangs from a ceiling?

**Comment by brewingcode** [comment]
Can you show a screenshot of what the cut-off right side looks like? I can't get it to happen.

**Comment by chrisglein** [comment]
Not happening for me anymore now. I suspect it needs the drop-down to fall on the right side of the text flow, and that's no longer happening.

![image](https://github.com/brewingcode/shanties/assets/26607885/c45426e9-9642-48e1-a3a9-c7b683870e02)

**Comment by chrisglein** [comment]
You can see how the dropdown clips in landscape rotation. But it's a bit more manageable here because you can adjust the scroll to get more of it in frame. When it happened in portrait there was literally no way to get it back in. 

![image](https://github.com/brewingcode/shanties/assets/26607885/bd5436b7-1d33-480b-b125-d635a67e0d3d)

No action needed now I think. If it happens again I'll go on a journey to bring in React and find a good dropdown replacement.

**Comment by brewingcode** [comment]
Thanks for the screeshots, glad it's not happening anymore. :P
