### ISSUE TITLE
Song Request: Ballad of the Mer

### ISSUE THREAD

**Issue by chrisglein** [brewingcode/shanties#4]
This one: https://open.spotify.com/track/6IqhOlJ3iitqTCqzk1BSbu?si=38c9fcf56209421e

Sheet music: https://musescore.com/user/40166470/scores/10040044

**Comment by brewingcode** [comment]
Here's a first crack at this. I just pulled out the "Violin 1" voice:

https://brewingcode.github.io/shanties/?file=ballad-of-the-mer.txt

**Comment by chrisglein** [comment]
With #5 this has been updated with lyrics. I also trimmed out the other parts because they should probably be overlaid, but I'm not sure how we'd want to do that. One of them should become the base chords I'm fairly sure. But can leave that for a future PR (many of the songs need matching chords). So closing this as done for now.
