### ISSUE TITLE
Render glitch on eighth notes when note labels turned on

### ISSUE THREAD

**Issue by chrisglein** [brewingcode/shanties#7]
![image](https://github.com/brewingcode/shanties/assets/26607885/41f1787b-48f8-49bd-982f-86e99db4a287)

**Comment by brewingcode** [comment]
I'm not thrilled with the hackiness of this fix, but I have failed to understand the rendering pipeline sufficiently for the different bits and bobs, so a hack it shall be until we find the next bug

https://github.com/brewingcode/abcjs/commit/29149033
